version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_USERNAME=mysql
      - DB_PASSWORD=mypass
      - DB_DATABASE_NAME=mydbuser
      - DB_PORT=3306
      - CRYPTO_SECRET_KEY=2345
      - API_PORT=8080
      - LOGLEVEL=debug
    restart: always
    networks:
      - my_app_network
      - my_db_network

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=mydbuser
    volumes:
      - ./src/v1/infrastructure/docker/db_volume:/var/lib/mysql
      - ./src/v1/infrastructure/docker/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - my_db_network

networks:
  my_app_network:
    driver: bridge
  my_db_network:
    driver: bridge
