# Use the latest MySQL image
FROM mysql:latest

# Define build arguments
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_DATABASE

# Set environment variables from build arguments
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
    MYSQL_DATABASE=$MYSQL_DATABASE

# Copy initialization scripts into the container
COPY scripts/ /docker-entrypoint-initdb.d/

# Volume for MySQL data
VOLUME ["/var/lib/mysql"]

# Expose MySQL port
EXPOSE 3306

# Healthcheck configuration to check if MySQL is up
HEALTHCHECK CMD mysqladmin ping -h localhost || exit 1

# Start MySQL when container starts
CMD ["mysqld"]