auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Enable the OpenTelemetry (OTLP) receiver for logs
# This is the key part for integrating with your OpenTelemetry collector
loki:
  ingester:
    lifecycler:
      # For a single instance, set the address to 127.0.0.1
      address: 127.0.0.1
  server:
    grpc_listen_port: 9095

# Configure the OTLP receiver
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9095
      http:
        endpoint: 0.0.0.0:9096

# Configure the exporter to write to Loki's local storage
exporters:
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push

# Create a pipeline for logs
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
