extensions:
  health_check: {} # Required for /metrics (default port: 13133)
  zpages: {} # For live debugging (default port: 55679)

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:54317
      http:
        endpoint: 0.0.0.0:54318

exporters:
  otlp/tempo:
    endpoint: tempo:64317
    tls:
      insecure: true
  debug:
    verbosity: detailed

processors:
  batch:
    timeout: 1s
    send_batch_size: 100

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
